# Part 1

In [191]:
import numpy as np
import pandas as pd

In [39]:
def ingest_data(opened_text_file):
    with open(opened_text_file) as f:
        puzzle_input = f.read().splitlines()
    
    coords = puzzle_input[:puzzle_input.index('')]
    folds = puzzle_input[puzzle_input.index('')+1:]
    
    coords = [(int(x.split(',')[0]), int(x.split(',')[1])) for x in coords]
    folds = [(x.split('=')[0][-1],int(x.split('=')[1])) for x in folds]
    
    return coords, folds

In [134]:
def new_val(val,fold_loc):
    return val - (val-fold_loc)*2

def new_dot(dots,fold):
    
    fold_loc = fold[1]
    horiz = fold[0] == 'y'
    
    if horiz:
        new_dots = [(dot[0],new_val(dot[1],fold_loc)) for dot in dots]
    else:
        new_dots = [(new_val(dot[0],fold_loc),dot[1]) for dot in dots]
        
    return new_dots

In [213]:
def get_rows_and_cols(coords):
    cols = [coord[0] for coord in coords]
    rows = [coord[1] for coord in coords] 
    
    return rows, cols

In [216]:
def day13(file,one_fold=True):
    
    coords, folds = ingest_data(file)
    
    rows, cols = get_rows_and_cols(coords)
    
    grid = np.zeros((max(rows)+1, max(cols)+1), dtype=int)
    
    grid[rows,cols] = 1
    
    # Fold the paper   
    
    if one_fold:
        folds = folds[:1]
        
    for fold in folds:
        
        fold_loc = fold[1]
        horiz_fold = int(fold[0]=='y')
                
        dots_to_move = [row for row in coords if row[horiz_fold] > fold_loc]
        dots_to_keep = [x for x in coords if x not in dots_to_move]

        new_dot_locs = new_dot(dots_to_move, fold)

        # Get new coords
        
        new_dot_rows, new_dot_cols = get_rows_and_cols(new_dot_locs)

        # Replace in the array
        grid[new_dot_rows,new_dot_cols] = 1 

        # Remove what we don't need        
        for loc in range(fold_loc,grid.shape[(1-horiz_fold)]):
            grid = np.delete(grid,fold_loc,(1-horiz_fold))          
            
        coords = dots_to_keep + new_dot_locs
        
    return grid

In [217]:
num_dots = np.count_nonzero(day13('puzzle_input.txt'))
num_dots

847

# Part 2

In [209]:
all_folds = day13('puzzle_input.txt',False)

In [212]:
pd.options.display.max_columns = all_folds.shape[1]
df_folds = pd.DataFrame(all_folds)
df_folds.replace(0, ' ', inplace=True)
df_folds

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
0,1,1,1,,,,1,1,,,1,1,1,1,,1,1,1,,,,1,1,,,1,1,1,1,,,1,1,,,1,1,1,,
1,1,,,1,,1,,,1,,,,,1,,1,,,1,,1,,,1,,1,,,,,1,,,1,,1,,,1,
2,1,1,1,,,1,,,,,,,1,,,1,,,1,,1,,,,,1,1,1,,,1,,,1,,1,1,1,,
3,1,,,1,,1,,,,,,1,,,,1,1,1,,,1,,,,,1,,,,,1,1,1,1,,1,,,1,
4,1,,,1,,1,,,1,,1,,,,,1,,1,,,1,,,1,,1,,,,,1,,,1,,1,,,1,
5,1,1,1,,,,1,1,,,1,1,1,1,,1,,,1,,,1,1,,,1,1,1,1,,1,,,1,,1,1,1,,

In [ ]:
# BCZRCEAB